# Configuración simple pero efectiva
run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Bugs/Errors
    - errcheck
    - gosec
    - govet
    - staticcheck

    # Code Quality
    - ineffassign
    - unused
    # - gocyclo
    # - gocognit
    # - dupl

    # Style
    # - gocritic
    # - unconvert
    # - unparam

    # Performance
    # - prealloc
    # - bodyclose

    # Best Practices
    # - exhaustive
    # - noctx
    # - rowserrcheck
    # - sqlclosecheck

errcheck:
  check-type-assertions: true
  check-blank: true

gosec:
  severity: medium
  confidence: medium

govet:
  check-shadowing: true
  enable-all: true

gocyclo:
  min-complexity: 15

dupl:
  threshold: 100

gocritic:
  enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style

issues:
  # Ignorar en tests
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

  # Límites razonables
  max-issues-per-linter: 30
  max-same-issues: 15