name: Golang Linting

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run golangci-lint v2
        uses: ./.github/actions/golangci-lint-v2
        with:
          go-version: '1.24'
          golangci-lint-version: '2.3.0'
          timeout: '3m'
          # Puedes agregar argumentos adicionales si es necesario
          args: '--verbose'