name: PR Validation

on:
  pull_request:
    types: [ opened, edited, synchronize ]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Solo añadir labels automáticos
      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

      # Chequear conflictos
      - name: Check conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "has-conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"